#ifndef INCLUDES_H_INCLUDED
#define INCLUDES_H_INCLUDED
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <math.h>
#include <random>
#include <time.h>
#include <vector>
#include "control.h"
#include "boundary.h"
#include "holm.h"
#include "kamen.h"
#include "brevno.h"
#include "pole.h"
#include "rover.h"
#include "processor.h"
#include <queue>
#include <ctime>
#include <cmath>
#endif // INCLUDES_H_INCLUDED
